name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: unzip -qu src/sqlite3.h.zip -d src; unzip -qu src/sqlite3.c.zip -d src; unzip -qu test/catch.hpp.zip -d test
    - name: make
      run: make -C sample && ./sample/sample
    - name: make test
      run: make -C test && ./test/test
